# Generated by Django 5.0.6 on 2024-09-29 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='carrer',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='exploreproperties',
            old_name='location',
            new_name='web_link',
        ),
    ]
