# Generated by Django 5.0.6 on 2024-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_carrer_carrier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsmedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('news_link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='newsphoto')),
            ],
        ),
        migrations.DeleteModel(
            name='media',
        ),
        migrations.RemoveField(
            model_name='unexplore',
            name='location',
        ),
    ]
