# Generated by Django 5.0.6 on 2024-10-02 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newsmedia_delete_media_remove_unexplore_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
