# Generated by Django 5.0.6 on 2024-10-02 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutphoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about')),
            ],
        ),
    ]
